updated docker file npm install script

diff --git a/posts/Dockerfile b/posts/Dockerfile
--- a/posts/Dockerfile
+++ b/posts/Dockerfile
@@ -4,9 +4,14 @@ RUN apk update && apk upgrade && apk add --no-cache --update nodejs npm
 
 WORKDIR /app
 
-COPY ./package.json ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 
-RUN npm install
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 COPY ./ ./
 
